# Generated by Django 4.2.9 on 2024-02-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackGround",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Название фона")),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/header", verbose_name="Изображение"
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Включен")),
            ],
            options={
                "verbose_name": "Фон",
                "verbose_name_plural": "Фоны панели",
            },
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, verbose_name="Название банера шапки"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/header", verbose_name="Изображение"
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Включен")),
            ],
            options={
                "verbose_name": "Шапка",
                "verbose_name_plural": "Шапка на главной",
            },
        ),
        migrations.CreateModel(
            name="Karta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Заголовок")),
                (
                    "image",
                    models.ImageField(upload_to="media/section", verbose_name="Фото"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Карта",
                "verbose_name_plural": "Карта ИКЦ",
            },
        ),
        migrations.CreateModel(
            name="PushkinKarta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Заголовок")),
                (
                    "image",
                    models.ImageField(upload_to="media/section", verbose_name="Фото"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Пушкинская карта",
                "verbose_name_plural": "Пушкинская карта",
            },
        ),
        migrations.CreateModel(
            name="QrCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название кода"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="media/qr", verbose_name="QR-code"),
                ),
            ],
            options={
                "verbose_name": "QR код",
                "verbose_name_plural": "QR коды",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название кружка"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="media/section", verbose_name="Фото"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Кружок",
                "verbose_name_plural": "Кружки",
            },
        ),
    ]
