# Generated by Django 4.2.9 on 2024-02-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="background",
            name="standart",
            field=models.BooleanField(default=False, verbose_name="Стандартный"),
        ),
        migrations.AddField(
            model_name="background",
            name="summer",
            field=models.BooleanField(default=False, verbose_name="Летний"),
        ),
        migrations.AddField(
            model_name="background",
            name="winter",
            field=models.BooleanField(default=False, verbose_name="Зимний"),
        ),
        migrations.AddField(
            model_name="header",
            name="standart",
            field=models.BooleanField(default=False, verbose_name="Стандартный"),
        ),
        migrations.AddField(
            model_name="header",
            name="summer",
            field=models.BooleanField(default=False, verbose_name="Летний"),
        ),
        migrations.AddField(
            model_name="header",
            name="winter",
            field=models.BooleanField(default=False, verbose_name="Зимний"),
        ),
    ]
