# Generated by Django 4.2.9 on 2024-02-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0002_background_standart_background_summer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="background",
            name="active",
        ),
        migrations.RemoveField(
            model_name="header",
            name="active",
        ),
    ]
