# Generated by Django 4.2.9 on 2024-02-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0003_remove_background_active_remove_header_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="background",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="media/header", verbose_name="Изображение"
            ),
        ),
    ]
