# Generated by Django 4.2.9 on 2024-03-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0004_alter_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Работает"),
        ),
    ]
