# Generated by Django 4.2.9 on 2024-03-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0006_pravila"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushkinCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Наименование")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="media/pushkin", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пушкинская карта",
                "verbose_name_plural": "Пушкинская карта",
            },
        ),
    ]
