# Generated by Django 4.2.9 on 2024-03-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0008_reglament"),
    ]

    operations = [
        migrations.CreateModel(
            name="Qr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Наименование")),
                (
                    "image",
                    models.ImageField(upload_to="media/qr-code", verbose_name="QR-код"),
                ),
            ],
            options={
                "verbose_name": "QR код",
                "verbose_name_plural": "QR коды",
            },
        ),
    ]
